version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:8080"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/react
    depends_on:
      - frontend
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - react_build:/frontend/build

  backend:
    build: ./backend/
    env_file:
      - .env
    environment:
      - CODE_ENV=prod
    volumes:
      - django_static:/usr/src/django-static/
    depends_on:
      - psqldb
      - fuseki
    ports:
      - "8000:8000"
    command: sh -c "python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py collectstatic --no-input &&
      gunicorn -w 3 -b 0.0.0.0:8000 --timeout 3600 --access-logfile - backend.wsgi:application"

  psqldb:
    image: postgres:latest
    restart: always
    volumes:
      - psqldata:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"


  fuseki:
    image: secoresearch/fuseki
    ports:
      - "3030:3030"
    environment:
      ADMIN_PASSWORD: 123456
      ENABLE_DATA_WRITE: "true"
      ENABLE_UPDATE: "true"
      ENABLE_UPLOAD: "true"
      QUERY_TIMEOUT: 10000
    volumes:
      - fuseki-data:/fuseki-base/databases
    container_name: fuseki
    stdin_open: true
    tty: true
    restart: unless-stopped


volumes:
  django_static:
  psqldata:
  fuseki-data:
  react_build:

