name: Test CI

env:
  PIPELINE_ID: ${{ github.run_id }}-${{ github.run_number }}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run Docker Compose
        run: docker-compose up -d

      - name: Run Backend Function Unit Test
        run: docker run --network host excel-interface-fuseki_backend /bin/sh -c "cd /backend/excelinterface && python -m unittest /backend/excelinterface/functions_test.py"
      
      - name: Run Backend Django Test
        run: docker run --network host excel-interface-fuseki_backend /bin/sh -c "cd / && python backend/manage.py test excelinterface"
